__METADATA__
{
  "v3Meta": {
    "objectGuid": "45a55bab-ee2c-4839-8b1c-610add9ea0ec",
    "objectTypeGuid": "6f9dac99-8de1-4efc-8465-68ac443b7d08",
    "embeddedObjectTypeGuids": [
      "a9ed5b7e-75c5-4651-af16-d2c27e98cb94",
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__DECLARATION__
PROGRAM TesteSTOP
VAR
	wLastStopCause : DWORD;
END_VAR
__IMPLEMENTATION__
wLastStopCause := PLC_R.i_wLastStopCause;
