__METADATA__
{
  "v3Meta": {
    "objectGuid": "da6d2041-057f-4fce-b2e0-75ad4c2f40c0",
    "objectTypeGuid": "6f9dac99-8de1-4efc-8465-68ac443b7d08",
    "embeddedObjectTypeGuids": [
      "a9ed5b7e-75c5-4651-af16-d2c27e98cb94",
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__DECLARATION__
PROGRAM A_PricipalGestao
VAR
END_VAR
__IMPLEMENTATION__
B_Acumuladores();
C_GerenciadorDatas();
