__METADATA__
{
  "v3Meta": {
    "objectGuid": "afe7322b-6d1a-4609-8002-2c686b6a31b4",
    "objectTypeGuid": "8ac092e5-3128-4e26-9e7e-11016c6684f2",
    "embeddedObjectTypeGuids": [
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__IMPLEMENTATION__
I_rTemperatura1:=rTermoparInferiorLeitura[1]/1;
I_rTemperatura2:=rTermoparInferiorLeitura[2]/1;
I_rTemperatura3:=rTermoparInferiorLeitura[3]/1;
I_rTemperatura4:=rTermoparInferiorLeitura[4]/1;
I_rTemperatura5:=rTermoparInferiorLeitura[5]/1;
I_rTemperatura6:=rTermoparInferiorLeitura[6]/1;
I_rTemperatura7:=rTermoparInferiorLeitura[7]/1;
I_rTemperatura8:=rTermoparInferiorLeitura[8]/1;
I_rTemperatura9:=rTermoparInferiorLeitura[9]/1;
I_rTemperatura10:=rTermoparInferiorLeitura[10]/1;

I_rTemperatura11:=rTermoparInferiorLeitura[11]/1;
I_rTemperatura12:=rTermoparInferiorLeitura[12]/1;
I_rTemperatura13:=rTermoparInferiorLeitura[13]/1;
I_rTemperatura14:=rTermoparInferiorLeitura[14]/1;
I_rTemperatura15:=rTermoparInferiorLeitura[15]/1;
I_rTemperatura16:=rTermoparInferiorLeitura[16]/1;
I_rTemperatura17:=rTermoparInferiorLeitura[17]/1;
I_rTemperatura18:=rTermoparInferiorLeitura[18]/1;
I_rTemperatura19:=rTermoparInferiorLeitura[19]/1;
I_rTemperatura20:=rTermoparInferiorLeitura[20]/1;

I_rTemperatura21:=rTermoparInferiorLeitura[21]/1;
I_rTemperatura22:=rTermoparInferiorLeitura[22]/1;
I_rTemperatura23:=rTermoparInferiorLeitura[23]/1;
I_rTemperatura24:=rTermoparInferiorLeitura[24]/1;
I_rTemperatura25:=rTermoparInferiorLeitura[25]/1;
I_rTemperatura26:=rTermoparInferiorLeitura[26]/1;
I_rTemperatura27:=rTermoparInferiorLeitura[27]/1;
I_rTemperatura28:=rTermoparInferiorLeitura[28]/1;
I_rTemperatura29:=rTermoparInferiorLeitura[29]/1;
I_rTemperatura30:=rTermoparInferiorLeitura[30]/1;
I_rTemperatura31:=rTermoparInferiorLeitura[31]/1;
I_rTemperatura32:=rTermoparInferiorLeitura[32]/1;
I_rTemperatura33:=rTermoparInferiorLeitura[33]/1;
I_rTemperatura34:=rTermoparInferiorLeitura[34]/1;
I_rTemperatura35:=rTermoparInferiorLeitura[35]/1;
I_rTemperatura36:=rTermoparInferiorLeitura[36]/1;
I_rTemperatura37:=rTermoparInferiorLeitura[37]/1;
I_rTemperatura38:=rTermoparInferiorLeitura[38]/1;
I_rTemperatura39:=rTermoparInferiorLeitura[39]/1;
I_rTemperatura40:=rTermoparInferiorLeitura[40]/1;
I_rTemperatura41:=rTermoparInferiorLeitura[41]/1;
I_rTemperatura42:=rTermoparInferiorLeitura[42]/1;
I_rTemperatura43:=rTermoparInferiorLeitura[43]/1;
I_rTemperatura44:=rTermoparInferiorLeitura[44]/1;
I_rTemperatura45:=rTermoparInferiorLeitura[45]/1;
I_rTemperatura46:=rTermoparInferiorLeitura[46]/1;
I_rTemperatura47:=rTermoparInferiorLeitura[47]/1;
I_rTemperatura48:=rTermoparInferiorLeitura[48]/1;
I_rTemperatura49:=rTermoparInferiorLeitura[49]/1;
I_rTemperatura50:=rTermoparInferiorLeitura[50]/1;

//superiores
I_rTemperatura51:=rTermoparSuperiorLeitura[1]/1;
I_rTemperatura52:=rTermoparSuperiorLeitura[2]/1;
I_rTemperatura53:=rTermoparSuperiorLeitura[3]/1;
I_rTemperatura54:=rTermoparSuperiorLeitura[4]/1;
I_rTemperatura55:=rTermoparSuperiorLeitura[5]/1;
I_rTemperatura56:=rTermoparSuperiorLeitura[6]/1;
I_rTemperatura57:=rTermoparSuperiorLeitura[7]/1;
I_rTemperatura58:=rTermoparSuperiorLeitura[8]/1;
I_rTemperatura59:=rTermoparSuperiorLeitura[9]/1;
I_rTemperatura60:=rTermoparSuperiorLeitura[10]/1;

I_rTemperatura61:=rTermoparSuperiorLeitura[11]/1;
I_rTemperatura62:=rTermoparSuperiorLeitura[12]/1;
I_rTemperatura63:=rTermoparSuperiorLeitura[13]/1;
I_rTemperatura64:=rTermoparSuperiorLeitura[14]/1;
I_rTemperatura65:=rTermoparSuperiorLeitura[15]/1;
I_rTemperatura66:=rTermoparSuperiorLeitura[16]/1;
I_rTemperatura67:=rTermoparSuperiorLeitura[17]/1;
I_rTemperatura68:=rTermoparSuperiorLeitura[18]/1;
I_rTemperatura69:=rTermoparSuperiorLeitura[19]/1;
I_rTemperatura70:=rTermoparSuperiorLeitura[20]/1;
I_rTemperatura71:=rTermoparSuperiorLeitura[21]/1;
I_rTemperatura72:=rTermoparSuperiorLeitura[22]/1;
I_rTemperatura73:=rTermoparSuperiorLeitura[23]/1;
I_rTemperatura74:=rTermoparSuperiorLeitura[24]/1;
I_rTemperatura75:=rTermoparSuperiorLeitura[25]/1;
I_rTemperatura76:=rTermoparSuperiorLeitura[26]/1;
I_rTemperatura77:=rTermoparSuperiorLeitura[27]/1;
I_rTemperatura78:=rTermoparSuperiorLeitura[28]/1;
I_rTemperatura79:=rTermoparSuperiorLeitura[29]/1;
I_rTemperatura80:=rTermoparSuperiorLeitura[30]/1;

I_rTemperatura81:=rTermoparSuperiorLeitura[31]/1;
I_rTemperatura82:=rTermoparSuperiorLeitura[32]/1;
I_rTemperatura83:=rTermoparSuperiorLeitura[33]/1;
I_rTemperatura84:=rTermoparSuperiorLeitura[34]/1;
I_rTemperatura85:=rTermoparSuperiorLeitura[35]/1;
I_rTemperatura86:=rTermoparSuperiorLeitura[36]/1;
I_rTemperatura87:=rTermoparSuperiorLeitura[37]/1;
I_rTemperatura88:=rTermoparSuperiorLeitura[38]/1;
I_rTemperatura89:=rTermoparSuperiorLeitura[39]/1;
I_rTemperatura90:=rTermoparSuperiorLeitura[40]/1;

I_rTemperatura91:=rTermoparSuperiorLeitura[41]/1;
I_rTemperatura92:=rTermoparSuperiorLeitura[42]/1;
I_rTemperatura93:=rTermoparSuperiorLeitura[43]/1;
I_rTemperatura94:=rTermoparSuperiorLeitura[44]/1;
I_rTemperatura95:=rTermoparSuperiorLeitura[45]/1;
I_rTemperatura96:=rTermoparSuperiorLeitura[46]/1;
I_rTemperatura97:=rTermoparSuperiorLeitura[47]/1;
I_rTemperatura98:=rTermoparSuperiorLeitura[48]/1;
I_rTemperatura99:=rTermoparSuperiorLeitura[49]/1;
I_rTemperatura100:=rTermoparSuperiorLeitura[50]/1;
